# This file was generated by GoReleaser. DO NOT EDIT.
class Goclone < Formula
  desc "Website Cloner - Utilizes powerful go routines to clone websites to your computer within seconds."
  homepage "https://github.com/imthaghost/goclone"
  version "1.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/imthaghost/goclone/releases/download/v1.0.0/goclone_1.0.0_macOS-64bit.tar.gz"
    sha256 "9a75c6b5c60d39a5209a7aa0d16afb7d3f7c2fba7a3141d8515db5bb676f86e9"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/imthaghost/goclone/releases/download/v1.0.0/goclone_1.0.0_Linux-64bit.tar.gz"
      sha256 "54f3d8008451f546d9f2c4f01319465ec0576b3c05869d66fc4b02d6eceb886a"
    end
  end

  def install
    bin.install "goclone"
  end
end
