# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goclone < Formula
  desc "Website Cloner - Utilizes powerful go routines to clone websites to your computer within seconds."
  homepage "https://github.com/imthaghost/goclone"
  version "1.2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/imthaghost/goclone/releases/download/v1.2.0/goclone_1.2.0_macOS-ARM64.tar.gz"
      sha256 "f319b31d5cd7d9b0bfcb1b0260aa72242216e33e58c75d6ca24613f867431c87"

      def install
        bin.install "goclone"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/imthaghost/goclone/releases/download/v1.2.0/goclone_1.2.0_macOS-64bit.tar.gz"
      sha256 "14f9f07413aac01d4e432f566a62c7a19bac58cfb91af71337b2ded19a145363"

      def install
        bin.install "goclone"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/imthaghost/goclone/releases/download/v1.2.0/goclone_1.2.0_Linux-ARM64.tar.gz"
      sha256 "5ae6ef45b41fc7786c6735c0bd429c25fd68e923ef6538ae5c528bda48f65393"

      def install
        bin.install "goclone"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/imthaghost/goclone/releases/download/v1.2.0/goclone_1.2.0_Linux-64bit.tar.gz"
      sha256 "b0df327ce713426dc0f11a87cc6e1120737310b817954ad8f5116a04cc8c885d"

      def install
        bin.install "goclone"
      end
    end
  end
end
