# This file was generated by GoReleaser. DO NOT EDIT.
class Goclone < Formula
  desc "Website Cloner - Utilizes powerful go routines to clone websites to your computer within seconds."
  homepage "https://github.com/imthaghost/goclone"
  version "1.1.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/imthaghost/goclone/releases/download/v1.1.1/goclone_1.1.1_macOS-64bit.tar.gz"
    sha256 "989b98bd628cf6342c8e74ca5a9ce0a2527babc73001d5abf6233ae4ce4ba5fa"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/imthaghost/goclone/releases/download/v1.1.1/goclone_1.1.1_Linux-64bit.tar.gz"
      sha256 "261ef861db36ffd446bbd184ce376d26579d7cdf6f98b7e75b44157b8ad4ca84"
    end
  end

  def install
    bin.install "goclone"
  end
end
